# See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware

    # nice-view-gem
    - name: m165437
      url-base: https://github.com/M165437

    # zmk-helpers, zmk-leader-key
    - name: urob
      url-base: https://github.com/urob

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

    # nice-view-gem
    - name: nice-view-gem
      remote: m165437
      revision: main

    # zmk-helpers
    # - name: zmk-helpers
    #   remote: urob
    #   revision: main

    # zmk-leader-key
    - name: zmk-leader-key
      remote: urob
      revision: main

  self:
    path: config
